# Generated by Django 2.2.4 on 2019-12-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='do',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='write something'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
