# Generated by Django 2.2.4 on 2019-12-28 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20191228_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('to-do', 'To Do'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='to-do', max_length=20, verbose_name='state')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='do',
        ),
        migrations.RemoveField(
            model_name='taskassignment',
            name='status',
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='decreption',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Task about'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='task_prority',
            field=models.CharField(choices=[('0_low', 'Low'), ('1_normal', 'Normal'), ('2_high', 'High'), ('3_critical', 'Critical'), ('4_blocker', 'Blocker')], default='10_normal', max_length=20, verbose_name='priority'),
        ),
    ]
