# Generated by Django 2.2.4 on 2019-12-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20191228_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignment',
            old_name='decreption',
            new_name='descreption',
        ),
    ]
