# Generated by Django 2.2.4 on 2019-12-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20191228_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='Taskdone',
        ),
    ]
