# Generated by Django 2.2.4 on 2019-12-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_auto_20191228_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdone',
            old_name='deadline',
            new_name='taskdone_at',
        ),
    ]
