# Generated by Django 2.2.4 on 2019-12-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20191228_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdone',
            name='taskdone',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Task done'),
        ),
    ]
